### ISSUE TITLE
try to  build in Android Studio but failed.

### ISSUE THREAD

**Issue by jinyulei0710** [nisrulz/flutter-examples#15]
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:558)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
	at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:699)
	at org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:691)
	at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
	at build_anlrty7ysz8l8nc1pf0y1wu6x$_run_closure2.doCall(/Users/jinyulei/Desktop/flutter-examples/stateless_widgets/android/build.gradle:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:983)
	at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:988)
	at org.gradle.api.internal.project.DefaultProject.subprojects(DefaultProject.java:971)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at build_anlrty7ysz8l8nc1pf0y1wu6x.run(/Users/jinyulei/Desktop/flutter-examples/stateless_widgets/android/build.gradle:24)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

**Comment by jinyulei0710** [comment]
* Error running Gradle:
ProcessException: Process
"/Users/jinyulei/Desktop/flutter-examples/simple_material_app/android/gradlew"
exited abnormally:

BUILD FAILED

Total time: 0.998 secs

Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary
configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:558)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at
	com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
	at
	org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(Br
	oadcastDispatch.java:93)
	at
	org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(Br
	oadcastDispatch.java:82)
	at
	org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastD
	ispatch.java:44)
	at
	org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at
	org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at
	org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.
	invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(
	LifecycleProjectEvaluator.java:82)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(Lifecycl
	eProjectEvaluator.java:76)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(Lifecycle
	ProjectEvaluator.java:33)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleP
	rojectEvaluator.java:53)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleP
	rojectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:106)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:61)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecyclePr
	ojectEvaluator.java:50)
	at
	org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628
	)
	at
	org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProje
	ct.java:699)
	at
	org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProje
	ct.java:691)
	at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
	at
	build_318aem33rluynzptia0ubzhmy$_run_closure2.doCall(/Users/jinyulei/Desktop/fl
	utter-examples/simple_material_app/android/build.gradle:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
	va:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at
	org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMeta
	Class.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at
	org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70
	)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at
	org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:98
	3)
	at
	org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:98
	8)
	at
	org.gradle.api.internal.project.DefaultProject.subprojects(DefaultProject.java:
	971)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
	va:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at
	org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(
	BeanDynamicObject.java:382)
	at
	org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject
	.java:170)
	at
	org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDyn
	amicObject.java:96)
	at
	org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.inv
	okeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at
	org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynam
	icObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
	va:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at
	org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClas
	sSite.java:69)
	at
	org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallS
	ite.java:166)
	at
	build_318aem33rluynzptia0ubzhmy.run(/Users/jinyulei/Desktop/flutter-examples/si
	mple_material_app/android/build.gradle:24)
	at
	org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.
	run(DefaultScriptRunnerFactory.java:90)
	at
	org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(Defa
	ultScriptPluginFactory.java:176)
	at
	org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarg
	et.java:77)
	at
	org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(Defa
	ultScriptPluginFactory.java:181)
	at
	org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProces
	sor.java:39)
	at
	org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProces
	sor.java:26)
	at
	org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(Conf
	igureActionsProjectEvaluator.java:34)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(Lifecycl
	eProjectEvaluator.java:70)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(Lifecycle
	ProjectEvaluator.java:33)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleP
	rojectEvaluator.java:53)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleP
	rojectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:106)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:61)
	at
	org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecyclePr
	ojectEvaluator.java:50)
	at
	org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628
	)
	at
	org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129
	)
	at
	org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluato
	r.java:35)
	at
	org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjec
	tEvaluator.java:60)
	at
	org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigure
	r.java:38)
	at
	org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher
	.java:161)
	at
	org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher
	.java:158)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:106)
	at
	org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOper
	ationExecutor.java:56)
	at
	org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLaun
	cher.java:158)
	at
	org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.j
	ava:119)
	at
	org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:
	102)
	at
	org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:7
	1)
	at
	org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildA
	ctionRunner.java:28)
	at
	org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunne
	r.java:35)
	at
	org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildAct
	ionExecuter.java:41)
	at
	org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildAct
	ionExecuter.java:26)
	at
	org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(Cont
	inuousBuildActionExecuter.java:75)
	at
	org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(Cont
	inuousBuildActionExecuter.java:49)
	at
	org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(S
	ervicesSetupBuildActionExecuter.java:44)
	at
	org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(S
	ervicesSetupBuildActionExecuter.java:29)
	at
	org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:6
	7)
	at
	org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnl
	y.java:36)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDi
	sconnection.java:47)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDepr
	ecationLogger.java:26)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(Re
	questStopIfSingleUsedDaemon.java:34)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientI
	nput.java:74)
	at
	org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientI
	nput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at
	org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClient
	Input.java:72)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHea
	lth.java:55)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at
	org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnl
	y.java:36)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(Establ
	ishBuildEnvironment.java:72)
	at
	org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnl
	y.java:36)
	at
	org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonComm
	andExecution.java:120)
	at
	org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartB
	uildOrRespondWithBusy.java:50)
	at
	org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoord
	inator.java:297)
	at
	org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(
	ExecutorPolicy.java:54)
	at
	org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImp
	l.java:40)
	at
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* Where:
Script
'/Users/jinyulei/development/flutter/packages/flutter_tools/gradle/flutter.gradl
e' line: 21

* What went wrong:
A problem occurred evaluating script.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
  Command:
  /Users/jinyulei/Desktop/flutter-examples/simple_material_app/android/gradlew
  app:properties


Please review your Gradle project setup in the android/ folder.

**Comment by nisrulz** [comment]
In order for you to open the project with Android Studio you need top point to the `android` folder when opening it. That way Android Studio knows it is an Android project and everything works as normal.

I am going to close this because all the examples works like this.
