### ISSUE TITLE
sample 'Image from Network' is not success, operation timeout

### ISSUE THREAD

**Issue by yuzhidi** [nisrulz/flutter-examples#41]
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                            9.2s
Syncing files to device iPhone Xʀ...

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following SocketException was thrown resolving an image codec:
OS Error: Operation timed out, errno = 60, address = raw.githubusercontent.com, port = 54151

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:88:43)
<asynchronous suspension>
#1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:48:14)
#2      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:48)
#3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
...
Image provider: NetworkImage("https://github.com/nisrulz/flutter-examples/raw/develop/image_from_network/img/flutter_logo.png", scale: 1.0)
Image key: NetworkImage("https://github.com/nisrulz/flutter-examples/raw/develop/image_from_network/img/flutter_logo.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by image resource service ════════════════════════════════════════════
OS Error: Operation timed out, errno = 60, address = raw.githubusercontent.com, port = 54152
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by nisrulz** [comment]
Is this happening only on iOS? 

I just tested on Android and everything was working as expected.
